services:
  - type: web
    name: root
    env: docker
    dockerfilePath: ./root/Dockerfile
    plan: free
    routes:
      - type: redirect
        source: /*
        destination: /index.html

  - type: web
    name: app-react
    env: docker
    dockerfilePath: ./app-react/Dockerfile
    plan: free

  - type: web
    name: app-vue
    env: docker
    dockerfilePath: ./app-vue/Dockerfile
    plan: free

  - type: web
    name: libs
    env: docker
    dockerfilePath: ./libs/Dockerfile
    plan: free

  - type: web
    name: nginx
    env: docker
    image: docker.io/library/nginx:latest
    plan: free
    # volumes:
    #   - path: ./default.conf
    #     mountPath: /etc/nginx/conf.d/default.conf
    # dependsOn:
    #   - root
    #   - app-react
    #   - app-vue
    #   - libs
