services:
  - type: web
    name: root
    env: docker
    dockerfilePath: "./root/Dockerfile"
    buildContext: "./root"
    ports:
      - port: 8080
        internal: 8080
    plan: free
    routes:
      - type: redirect
        source: /*
        destination: /index.html

  - type: web
    name: app-react
    env: docker
    dockerfilePath: "./app-react/Dockerfile"
    buildContext: "./app-react"
    ports:
      - port: 8080
        internal: 8080
    plan: free

  - type: web
    name: app-vue
    env: docker
    dockerfilePath: ./app-vue/Dockerfile
    buildContext: ./app-vue
    ports:
      - port: 8080
        internal: 8080
    plan: free

  - type: web
    name: libs
    env: docker
    dockerfilePath: "./libs/Dockerfile"
    buildContext: ./libs
    ports:
      - port: 8080
        internal: 8080
    plan: free

  - type: web
    name: nginx
    env: docker
    image: nginx
    ports:
      - port: 8080
        internal: 80
    plan: free
    volumes:
      - path: ./default.conf
        mountPath: /etc/nginx/conf.d/default.conf
    dependsOn:
      - root
      - app-react
      - app-vue
      - libs
